// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(PublishContext))]
    [Migration("20210902100342_Test_AddOldArticles")]
    partial class Test_AddOldArticles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdAuthor")
                        .HasColumnType("int")
                        .HasColumnName("id_author");

                    b.Property<string>("Name")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime")
                        .HasColumnName("publish_date");

                    b.HasKey("Id")
                        .HasName("articles_pk")
                        .IsClustered(false);

                    b.HasIndex("IdAuthor");

                    b.ToTable("articles", "dbadmin");
                });

            modelBuilder.Entity("DataAccess.Entities.ArticleOld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TextId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TextId");

                    b.ToTable("OldArticle");
                });

            modelBuilder.Entity("DataAccess.Entities.ArticleTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int?>("IdTag")
                        .HasColumnType("int")
                        .HasColumnName("id_tag");

                    b.HasKey("Id")
                        .HasName("article_tags_pk")
                        .IsClustered(false);

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdTag");

                    b.ToTable("article_tags", "dbadmin");
                });

            modelBuilder.Entity("DataAccess.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime")
                        .HasColumnName("join_date");

                    b.Property<string>("Name")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("authors_pk")
                        .IsClustered(false);

                    b.ToTable("authors", "dbadmin");
                });

            modelBuilder.Entity("DataAccess.Entities.InfoOld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("NumOfSigns")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OldInfo");
                });

            modelBuilder.Entity("DataAccess.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tags_pk")
                        .IsClustered(false);

                    b.ToTable("tags", "dbadmin");

                    b
                        .HasComment("desc tags for articles");
                });

            modelBuilder.Entity("DataAccess.Entities.Text", b =>
                {
                    b.Property<bool?>("AdultOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("adult_only")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Data")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("data");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int?>("ReaderRating")
                        .HasColumnType("int")
                        .HasColumnName("reader_rating");

                    b.HasIndex(new[] { "IdArticle" }, "texts_id_article_uindex")
                        .IsUnique();

                    b.ToTable("texts", "dbadmin");
                });

            modelBuilder.Entity("DataAccess.Entities.Article", b =>
                {
                    b.HasOne("DataAccess.Entities.Author", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("IdAuthor")
                        .HasConstraintName("articles_authors_id_fk")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DataAccess.Entities.ArticleOld", b =>
                {
                    b.HasOne("DataAccess.Entities.InfoOld", "Text")
                        .WithMany()
                        .HasForeignKey("TextId");

                    b.Navigation("Text");
                });

            modelBuilder.Entity("DataAccess.Entities.ArticleTag", b =>
                {
                    b.HasOne("DataAccess.Entities.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("IdArticle")
                        .HasConstraintName("article_tags_articles_id_fk")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataAccess.Entities.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("IdTag")
                        .HasConstraintName("article_tags_tags_id_fk")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DataAccess.Entities.Text", b =>
                {
                    b.HasOne("DataAccess.Entities.Article", "Article")
                        .WithOne()
                        .HasForeignKey("DataAccess.Entities.Text", "IdArticle")
                        .HasConstraintName("texts_articles_id_fk")
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("DataAccess.Entities.Article", b =>
                {
                    b.Navigation("ArticleTags");
                });

            modelBuilder.Entity("DataAccess.Entities.Author", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("DataAccess.Entities.Tag", b =>
                {
                    b.Navigation("ArticleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
